let data=JSON.parse(localStorage.getItem("dh_exact")||"[]"),current=-1;const $=x=>document.getElementById(x);
function login(){if($("user").value==="admin"&&$("pass").value==="password"){$("login").hidden=true;$("dashboard").hidden=false;draw()}else alert("Tài khoản hoặc mật khẩu không đúng.")}
function logout(){$("dashboard").hidden=true;$("login").hidden=false}
function showCreate(){$("create").hidden=false}function hideCreate(){$("create").hidden=true}
function key(){let r=n=>Array.from({length:n},()=>Math.floor(Math.random()*10)).join("");return`Dark-${r(3)}-${r(3)}-${r(3)}-${r(4)}`}
function createScript(){let name=$("name").value.trim(),code=$("code").value.trim();if(!name||!code)return alert("Hãy nhập tên và nội dung script.");data.unshift({name,desc:$("desc").value.trim(),code,key:key(),on:$("status").value==="1",runs:0});save();["name","desc","code"].forEach(x=>$(x).value="");hideCreate()}
function save(){localStorage.setItem("dh_exact",JSON.stringify(data));draw()}
function draw(){$("count").textContent=data.length;$("active").textContent=data.filter(x=>x.on).length;$("runs").textContent=data.reduce((a,x)=>a+x.runs,0);$("cards").innerHTML=data.map((x,i)=>`<article class="card"><div class="card-title"><div class="icon">‹/›</div><div><h3>${safe(x.name)} <span class="badge">${x.on?"Đang bật":"Đã tắt"}</span></h3><div class="meta">${safe(x.desc||"Không có mô tả")}</div></div></div><div class="meta">▷ ${x.runs} lượt chạy　•　${x.key}</div><div class="code-row"><code>${safe(x.code)}</code><button class="outline" onclick="copyCode(${i})">▣ Copy</button></div><div class="card-actions"><button class="red-btn" onclick="toggle(${i})">${x.on?"◉ Tắt script":"◉ Bật script"}</button><button class="outline" onclick="edit(${i})">✎ Chỉnh sửa</button><button class="outline" onclick="removeItem(${i})">♜ Xoá</button><button class="outline" onclick="protect(${i})">🔒 Bảo vệ</button></div></article>`).join("")||'<p class="meta">Chưa có script nào.</p>'}
function toggle(i){data[i].on=!data[i].on;save()}function removeItem(i){if(confirm("Xoá script này?")){data.splice(i,1);save()}}function edit(i){let n=prompt("Tên script:",data[i].name);if(n){data[i].name=n;save()}}function copyCode(i){navigator.clipboard?.writeText(data[i].code);alert("Đã copy nội dung script.")}
function protect(i){current=i;$("key").value="";$("protect").hidden=false}function hideProtect(){$("protect").hidden=true}function unlock(){if(current<0)return;let x=data[current];if($("key").value.trim()===x.key){x.runs++;save();hideProtect();alert("Mã đúng — script đã được mở khoá.")}else alert("Mã bảo mật không đúng.")}
function safe(s){return String(s).replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]))}draw();